apiVersion: v1alpha1
kind: Setting
metadata:
    name: halo-theme-archer-setting
spec:
    forms:
        - group: basic
          label: 基础设置
          formSchema:
              - $formkit: text
                name: main_title
                label: 主标题
                value: "Archer's Blog"
              - $formkit: text
                name: subtitle
                label: 副标题
                value: "it's better to burn out than to fade away"

        - group: profile
          label: 个人资料
          formSchema:
              - $formkit: attachment
                name: avatar
                label: 头像
                value: '/avatar/Misaka.jpg'
              - $formkit: text
                name: author
                label: 作者名
                value: 'Azincc'
              - $formkit: text
                name: signature
                label: 个性签名
                value: 'witness me'
              - $formkit: repeater
                name: social
                label: 社交链接
                children:
                    - $formkit: text
                      name: name
                      label: '名称'
                      validation: 'required'
                    - $formkit: text
                      name: url
                      label: 链接
                    - $formkit: text
                      name: icon
                      label: 图标
                      description: 'Font Awesome icon class, e.g., fab fa-github'
                value:
                    - name: 'github'
                      url: '//github.com/Azincc'
                      icon: 'fab fa-github'
                    - name: 'email'
                      url: 'mailto:12345@qq.com'
                      icon: 'fas fa-envelope'
              - $formkit: repeater
                name: friends
                label: 友情链接
                children:
                    - $formkit: text
                      name: name
                      label: '名称'
                      validation: 'required'
                    - $formkit: text
                      name: url
                      label: '链接'
                      validation: 'required'
              - $formkit: group
                name: profile_icons
                label: '个人资料图标'
                children:
                    - $formkit: checkbox
                      name: enable
                      label: '启用'
                      value: false
                    - $formkit: text
                      name: friends
                      label: '友链图标'
                      value: 'fas fa-heart'
                    - $formkit: text
                      name: about
                      label: '关于图标'
                      value: 'fas fa-id-card'
                    - $formkit: text
                      name: search
                      label: '搜索图标'
                      value: 'fas fa-search'
              - $formkit: repeater
                name: profile_links
                label: '附加个人链接'
                children:
                    - $formkit: text
                      name: name
                      label: '名称'
                    - $formkit: text
                      name: url
                      label: '链接'
                    - $formkit: text
                      name: icon
                      label: '图标'

        - group: style
          label: 风格设置
          formSchema:
              - $formkit: select
                name: color_scheme
                label: 默认配色
                value: system
                options:
                    - label: 跟随系统
                      value: system
                    - label: 深色
                      value: dark
                    - label: 浅色
                      value: light
              - $formkit: color
                name: main_color_light
                label: 浅色主题强调色
                value: '#f75357'
              - $formkit: color
                name: main_color_dark
                label: 深色主题强调色
                value: '#f75357'
              - $formkit: attachment
                name: site_header_image
                label: 首页顶部图片
                value: ''
              - $formkit: attachment
                name: tag_header_image
                label: 标签页顶部图片
                value: ''
              - $formkit: attachment
                name: category_header_image
                label: 分类页顶部图片
                value: ''
              - $formkit: attachment
                name: post_header_image
                label: 文章页顶部图片
                value: ''
              - $formkit: attachment
                name: about_header_image
                label: 关于页顶部图片
                value: ''
              - $formkit: attachment
                name: _404_header_image
                label: 404页顶部图片
                value: ''
              - $formkit: number
                name: index_intro_height
                label: 首页简介高度
                value: 50
              - $formkit: number
                name: post_intro_height
                label: 文章页简介高度
                value: 50
              - $formkit: number
                name: about_intro_height
                label: 关于页简介高度
                value: 50
              - $formkit: radio
                name: float_button_theme
                label: 浮动按钮主题
                options:
                    - label: 默认
                      value: value
                    - label: 圆形
                      value: rounded
                value: value
              - $formkit: radio
                name: read_progress_color
                label: 阅读进度条颜色
                options:
                    - label: 默认
                      value: value
                    - label: 特色
                      value: feature
                value: value
              - $formkit: radio
                name: post_banner_theme
                label: 文章页横幅主题
                options:
                    - label: 默认
                      value: value
                    - label: 简洁
                      value: clean
                value: value
              - $formkit: checkbox
                name: avatar_border
                label: 显示头像边框
                value: true
              - $formkit: checkbox
                name: profile_sticky
                label: 固定个人资料
                value: false
              - $formkit: checkbox
                name: show_categories
                label: 显示文章分类
                value: false
              - $formkit: checkbox
                name: enable_rich_excerpt
                label: '启用富文本摘要'
                value: false

              - $formkit: checkbox
                name: read_more_button
                label: '显示阅读更多按钮'
                value: false
              - $formkit: checkbox
                name: toc
                label: '启用文章目录'
                value: true
              - $formkit: checkbox
                name: reading_info
                label: '显示字数和阅读时间'
                value: false

        - group: social_meta
          label: 社交媒体
          formSchema:
              - $formkit: text
                name: twitter_id
                label: Twitter ID
                help: Twitter 用户名（不含 @）
              - $formkit: text
                name: fb_admins
                label: Facebook 管理员 ID
              - $formkit: text
                name: fb_app_id
                label: Facebook App ID

        - group: donate
          label: 赞赏设置
          formSchema:
              - $formkit: checkbox
                name: enable
                label: 启用
                value: false
              - $formkit: text
                name: title
                label: 标题
                value: 'Buy Me A Coffee'
              - $formkit: textarea
                name: description
                label: 描述
                value: 'If this post helped you, please consider buying the author a cup of sugar-free coffee ☕️.'
              - $formkit: repeater
                name: qr_codes
                label: 二维码
                addLabel: '添加二维码'
                children:
                    - $formkit: attachment
                      name: image
                      label: '二维码图片'
                value: []

        - group: analytics
          label: 分析统计
          formSchema:
              - $formkit: text
                name: baidu_analytics
                label: 百度统计 ID
              - $formkit: text
                name: google_analytics
                label: 谷歌统计 ID
              - $formkit: text
                name: CNZZ_analytics
                label: 'CNZZ 统计 ID'
              - $formkit: group
                name: busuanzi
                label: '统计'
                children:
                    - $formkit: checkbox
                      name: enable
                      label: '启用'
                      value: true
                    - $formkit: text
                      name: slug
                      label: '显示文本'
                      value: '本站访客数${count}人次'
                      help: '使用 ${count} 作为占位符显示统计数字'

        - group: footer
          label: 页脚
          formSchema:
              - $formkit: group
                name: beian
                label: 备案信息
                children:
                    - $formkit: checkbox
                      name: enable
                      label: 启用备案信息
                      value: false
                    - $formkit: text
                      name: number
                      label: 备案号
              - $formkit: repeater
                name: sfooter_info
                label: 自定义底部信息
                value: []
                children:
                    - $formkit: text
                      name: sf_title
                      label: 信息文本
                    - $formkit: text
                      name: sf_link
                      label: 信息链接
                    - $formkit: attachment
                      name: sf_img
                      label: 图标
                      accepts:
                          - 'image/*'
              - $formkit: checkbox
                name: show_stats
                key: show_stats
                id: show_stats
                label: 显示统计信息
                value: true
                help: 在站点底部显示全站的统计信息

        - group: other
          label: 其他设置
          formSchema:
              - $formkit: group
                name: copyright
                children:
                    - $formkit: checkbox
                      name: enable
                      label: 启用版权信息
                      value: true
                    - $formkit: text
                      name: license
                      label: 许可协议
                      value: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
              - $formkit: group
                name: outdated_threshold
                label: '文章时效性提示'
                children:
                    - $formkit: checkbox
                      name: enable
                      label: '启用'
                      value: false
                    - $formkit: number
                      name: days
                      label: '阈值天数'
                      value: 180
                    - $formkit: checkbox
                      name: specify_article
                      label: '为指定文章启用'
                      value: false
              - $formkit: group
                name: mermaid
                label: 'Mermaid 图表'
                children:
                    - $formkit: checkbox
                      name: enable
                      label: '启用'
                      value: false
                    - $formkit: text
                      name: version
                      label: '版本'
                      value: '8.11.0'
                    - $formkit: text
                      name: theme
                      label: '主题'
                      value: 'dark'
              - $formkit: group
                name: math
                label: 'LaTeX 数学公式'
                children:
                    - $formkit: group
                      name: mathjax
                      children:
                          - $formkit: checkbox
                            name: enable
                            label: '启用 MathJax'
                            value: false
                          - $formkit: text
                            name: version
                            label: '版本'
                            value: '3.2.0'
              - $formkit: group
                name: custom_font
                label: '自定义字体'
                children:
                    - $formkit: checkbox
                      name: enable
                      label: '启用'
                      value: false
                    - $formkit: text
                      name: name
                      label: '字体名称'
                      value: 'Noto Sans SC:n3,n4,n5,n7'
                    - $formkit: text
                      name: url
                      label: '字体 CDN URL'
                      value: 'https://fonts.googleapis.cnpmjs.org/css2?family=Noto+Sans+SC:wght@300;400;500;700&display=swap'
